services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:///data/messages.db
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/app/data

volumes:
  backend-data:
