services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:///data/messages.db
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/app/data
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  backend-data:
  qdrant-storage:
